### ISSUE TITLE
Did you incorporate open surface data in addition to watertight data?

### ISSUE THREAD

**Issue by ZENGYIMING-EAMON** [raphaelsulzer/dsr-benchmark#1]

**Comment by ZENGYIMING-EAMON** [comment]
By the way, are you planning to include the rendering techniques used to create Figure 5 in your survey paper: A Survey and Benchmark of Automatic Surface Reconstruction from Point Clouds ?

**Comment by raphaelsulzer** [comment]
Hi,
the surfaces in Experiment 8 / Figure 6 are basically all open surfaces. Especially the Truck from Tanks and Temples and scan1 (the bucket) from DTU.

You can find the script which generates the plots of Figure 5 in this repo in `figures/model_plots/blender.py` .
