### ISSUE TITLE
There is no way to use a different dataset than the ones provided.

### ISSUE THREAD

**Issue by sLaera** [raphaelsulzer/dsr-benchmark#3]
There is no official method defined for adding a custom dataset. Users currently do not have a standardized process or guidelines to follow when attempting to incorporate their own datasets into the system.

**Comment by raphaelsulzer** [comment]
Hi,

you can inherit from the `DefaultDataset` class in `dsrb/datasets/default_dataset.py`. Then you have to add your custom `get_models()` function, for which you can find examples in all the provided datasets, e.g. `dsrb/datasets/modelnet10.py` has one.
