### ISSUE TITLE
Synthetic range scan

### ISSUE THREAD

**Issue by sLaera** [raphaelsulzer/dsr-benchmark#5]
The documentation explains how to perform a synthetic MVS scan, but it is not clear how to conduct a range scan.

Is there a way to use the scan function to accomplish this task? If not, could you clarify how the range scan described in the paper was performed?

**Comment by raphaelsulzer** [comment]
It is fully based on Berger et al. You can find the code [here](https://github.com/raphaelsulzer/reconbench-CMake). But the dataset used in the benchmark is provided in this repo and includes the range scans.

**Comment by sLaera** [comment]
thank you, now is more clear
